<?php

// بررسی دسترسی کاربر
require_once __DIR__ . '/check_access.php';
requireAccess(basename(__FILE__));
if (session_status() === PHP_SESSION_NONE) { session_start(); }
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/jdf.php';

// Initialize variables
$success = '';
$error = '';
$backupFiles = [];
$backupDir = __DIR__ . '/../backups/';
$maxFileSize = 500 * 1024 * 1024; // 500MB max file size for uploads

// Handle file deletion
if (isset($_GET['delete'])) {
    $fileToDelete = basename($_GET['delete']);
    $filePath = $backupDir . $fileToDelete;
    
    // Security check: Only allow deleting .zip and .sql files from the backup directory
    if (file_exists($filePath) && 
        (pathinfo($filePath, PATHINFO_EXTENSION) === 'zip' || 
         pathinfo($filePath, PATHINFO_EXTENSION) === 'sql') &&
        strpos(realpath($filePath), realpath($backupDir)) === 0) {
        
        if (unlink($filePath)) {
            $success = 'فایل پشتیبان با موفقیت حذف شد.';
            // Redirect to avoid resubmission
            header('Location: ' . $_SERVER['PHP_SELF'] . '?success=' . urlencode($success));
            exit();
        } else {
            $error = 'خطا در حذف فایل پشتیبان.';
        }
    } else {
        $error = 'فایل نامعتبر یا عدم دسترسی.';
    }
}

// Create backup directory if it doesn't exist
if (!is_dir($backupDir)) {
    if (!mkdir($backupDir, 0755, true)) {
        $error = 'خطا در ایجاد پوشه پشتیبان‌گیری';
    }
}

// Function to create database dump using PHP
function createDatabaseDump($connection, $databaseName) {
    $dump = "-- MySQL dump generated by PHP\n";
    $dump .= "-- Database: `{$databaseName}`\n";
    $dump .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
    $dump .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    $dump .= "START TRANSACTION;\n";
    $dump .= "SET time_zone = \"+00:00\";\n\n";
    
    // Get all tables
    $tables = [];
    $result = $connection->query("SHOW TABLES");
    while ($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }
    
    foreach ($tables as $table) {
        $dump .= "\n-- --------------------------------------------------------\n";
        $dump .= "-- Table structure for table `{$table}`\n";
        $dump .= "-- --------------------------------------------------------\n\n";
        
        // Get table structure
        $createTable = $connection->query("SHOW CREATE TABLE `{$table}`");
        $createRow = $createTable->fetch_row();
        $dump .= "DROP TABLE IF EXISTS `{$table}`;\n";
        $dump .= $createRow[1] . ";\n\n";
        
        // Get table data
        $dump .= "-- Dumping data for table `{$table}`\n\n";
        $dataResult = $connection->query("SELECT * FROM `{$table}`");
        $numRows = $dataResult->num_rows;
        
        if ($numRows > 0) {
            $dump .= "INSERT INTO `{$table}` VALUES\n";
            $values = [];
            while ($row = $dataResult->fetch_row()) {
                $rowValues = [];
                foreach ($row as $value) {
                    if ($value === null) {
                        $rowValues[] = 'NULL';
                    } else {
                        $rowValues[] = "'" . $connection->real_escape_string($value) . "'";
                    }
                }
                $values[] = '(' . implode(', ', $rowValues) . ')';
            }
            $dump .= implode(",\n", $values) . ";\n";
        }
        $dump .= "\n";
    }
    
    $dump .= "COMMIT;\n";
    return $dump;
}

// Function to add directory recursively to zip
function addDirectoryToZip($zip, $directory, $base = '') {
    if (!is_dir($directory)) {
        return;
    }
    
    $files = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($directory, RecursiveDirectoryIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );
    
    foreach ($files as $file) {
        $filePath = $file->getRealPath();
        $relativePath = $base . '/' . str_replace('\\', '/', substr($filePath, strlen($directory) + 1));
        
        if ($file->isDir()) {
            $zip->addEmptyDir(trim($relativePath, '/'));
        } else {
            $zip->addFile($filePath, trim($relativePath, '/'));
        }
    }
}

// Handle database backup
if (isset($_GET['action']) && $_GET['action'] === 'backup_db') {
    try {
        $backupName = 'db_backup_' . date('Y-m-d_His') . '.sql';
        $backupFile = $backupDir . $backupName;
        
        // Create database dump
        $dump = createDatabaseDump($conn, DB_NAME);
        
        // Save to file
        if (file_put_contents($backupFile, $dump) !== false) {
            $success = 'پشتیبان‌گیری از دیتابیس با موفقیت انجام شد: ' . $backupName;
            // Redirect to prevent resubmission
            header('Location: ' . $_SERVER['PHP_SELF'] . '?success=' . urlencode($success));
            exit();
        } else {
            throw new Exception('خطا در ذخیره فایل پشتیبان');
        }
    } catch (Exception $e) {
        $error = 'خطا در ایجاد پشتیبان از دیتابیس: ' . $e->getMessage();
    }
}

// Handle full backup creation
if (isset($_GET['action']) && $_GET['action'] === 'create_backup') {
    try {
        $backupName = 'backup_' . jdate('Y-m-d_His', time(), '', 'Asia/Tehran', 'en') . '.zip';
        $backupPath = $backupDir . $backupName;
        
        // Check available disk space (need at least 500MB free)
        $freeSpace = disk_free_space(__DIR__);
        if ($freeSpace < 500 * 1024 * 1024) {
            throw new Exception('فضای دیسک کافی نیست. لطفاً ابتدا فضای کافی ایجاد کنید.');
        }
        
        // Create new zip archive
        $zip = new ZipArchive();
        if ($zip->open($backupPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== TRUE) {
            throw new Exception('خطا در ایجاد فایل زیپ');
        }

        // Create database dump using PHP method
        $dbDumpContent = createDatabaseDump($conn, DB_NAME);
        $dbDump = tempnam(sys_get_temp_dir(), 'db_dump_') . '.sql';
        file_put_contents($dbDump, $dbDumpContent);
        
        if (!file_exists($dbDump) || filesize($dbDump) === 0) {
            throw new Exception('خطا در ایجاد فایل دامپ دیتابیس');
        }
        
        $zip->addFile($dbDump, 'database.sql');
        
        // Add root directory files and folders to zip (excluding backups and temp files)
        $rootDir = dirname(__DIR__); // This is the root directory of the website
        
        // Define directories and files to exclude
        $excludePatterns = [
            '/backups/',
            '/tmp/',
            '/temp/',
            '/cache/',
            '/log/',
            '.git',
            '.svn',
            '.DS_Store',
            'Thumbs.db',
            '*.tmp',
            'backup_*.zip'
        ];
        
        $files = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($rootDir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );
        
        foreach ($files as $file) {
            $filePath = $file->getRealPath();
            $relativePath = str_replace('\\', '/', substr($filePath, strlen($rootDir) + 1));
            
            // Skip excluded patterns
            $shouldExclude = false;
            foreach ($excludePatterns as $pattern) {
                if (fnmatch($pattern, basename($filePath)) || 
                    strpos($relativePath, trim($pattern, '/')) === 0) {
                    $shouldExclude = true;
                    break;
                }
            }
            
            if ($shouldExclude) {
                continue;
            }
            
            if ($file->isDir()) {
                $zip->addEmptyDir($relativePath);
            } else {
                $zip->addFile($filePath, $relativePath);
            }
        }
        
        // Close zip and clean up
        $zip->close();
        @unlink($dbDump);
        
        $success = 'پشتیبان‌گیری با موفقیت انجام شد. فایل: ' . $backupName;
    } catch (Exception $e) {
        $error = $e->getMessage();
        if (isset($zip) && $zip) {
            $zip->close();
        }
        if (isset($dbDump) && file_exists($dbDump)) {
            @unlink($dbDump);
        }
    }
}

// Handle backup restoration
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'restore') {
    try {
        if (!isset($_FILES['backup_file']) || $_FILES['backup_file']['error'] !== UPLOAD_ERR_OK) {
            $uploadError = $_FILES['backup_file']['error'] ?? -1;
            $errorMessages = [
                UPLOAD_ERR_INI_SIZE => 'حجم فایل آپلود شده از حد مجاز بیشتر است',
                UPLOAD_ERR_FORM_SIZE => 'حجم فایل آپلود شده از حد مجاز فرم بیشتر است',
                UPLOAD_ERR_PARTIAL => 'فایل آپلود شده به صورت ناقص آپلود شده است',
                UPLOAD_ERR_NO_FILE => 'هیچ فایلی آپلود نشده است',
                UPLOAD_ERR_NO_TMP_DIR => 'پوشه موقت وجود ندارد',
                UPLOAD_ERR_CANT_WRITE => 'خطا در نوشتن فایل بر روی دیسک',
                UPLOAD_ERR_EXTENSION => 'آپلود فایل توسط یک افزونه PHP متوقف شد'
            ];
            throw new Exception($errorMessages[$uploadError] ?? 'خطای ناشناخته در آپلود فایل');
        }
        
        // Check file size
        if ($_FILES['backup_file']['size'] > $maxFileSize) {
            throw new Exception('حجم فایل نباید بیشتر از ' . formatSize($maxFileSize) . ' باشد');
        }
        
        // Check file type
        $fileType = strtolower(pathinfo($_FILES['backup_file']['name'], PATHINFO_EXTENSION));
        if ($fileType !== 'zip') {
            throw new Exception('فقط فایل‌های با فرمت ZIP قابل قبول هستند');
        }
        
        $file = $_FILES['backup_file'];
        $tempDir = sys_get_temp_dir() . '/backup_restore_' . uniqid();
        
        if (!mkdir($tempDir)) {
            throw new Exception('خطا در ایجاد پوشه موقت');
        }
        
        // Extract zip file
        $zip = new ZipArchive();
        if ($zip->open($file['tmp_name']) !== TRUE) {
            throw new Exception('خطا در باز کردن فایل زیپ');
        }
        
        if (!$zip->extractTo($tempDir)) {
            $zip->close();
            throw new Exception('خطا در استخراج فایل زیپ');
        }
        $zip->close();
        
        // Restore database if dump exists
        $dbDump = $tempDir . '/database.sql';
        if (file_exists($dbDump)) {
            $sql = file_get_contents($dbDump);
            $sql = str_replace("\r\n", "\n", $sql);
            $sql = str_replace("\r", "\n", $sql);
            $sqlArray = explode(";\n", $sql);
            
            foreach ($sqlArray as $stmt) {
                $stmt = trim($stmt);
                if (!empty($stmt) && strpos($stmt, '--') !== 0) {
                    if (!$conn->query($stmt)) {
                        throw new Exception('خطا در اجرای کوئری: ' . $conn->error);
                    }
                }
            }
        }
        
        // Restore files to root directory
        $rootDir = dirname(__DIR__);
        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($tempDir, RecursiveDirectoryIterator::SKIP_DOTS),
            RecursiveIteratorIterator::SELF_FIRST
        );
        
        foreach ($iterator as $item) {
            $relativePath = substr($item->getPathname(), strlen($tempDir));
            $targetPath = $rootDir . '/' . ltrim($relativePath, '/');
            
            // Skip database.sql as it's already processed
            if (basename($item->getPathname()) === 'database.sql') {
                continue;
            }
            
            if ($item->isDir()) {
                if (!is_dir($targetPath)) {
                    mkdir($targetPath, 0755, true);
                }
            } else {
                $targetDir = dirname($targetPath);
                if (!is_dir($targetDir)) {
                    mkdir($targetDir, 0755, true);
                }
                
                if (!copy($item->getPathname(), $targetPath)) {
                    throw new Exception('خطا در کپی فایل: ' . $targetPath);
                }
            }
        }
        
        // Clean up
        rrmdir($tempDir);
        $success = 'بازیابی با موفقیت انجام شد.';
        
    } catch (Exception $e) {
        $error = $e->getMessage();
        if (isset($tempDir) && is_dir($tempDir)) {
            rrmdir($tempDir);
        }
    }
}

// Get list of backup files
if (is_dir($backupDir)) {
    $files = scandir($backupDir, SCANDIR_SORT_DESCENDING);
    foreach ($files as $file) {
        if ($file !== '.' && $file !== '..' && (pathinfo($file, PATHINFO_EXTENSION) === 'zip' || pathinfo($file, PATHINFO_EXTENSION) === 'sql')) {
            $filePath = $backupDir . $file;
            $fileInfo = [
                'name' => $file,
                'size' => filesize($filePath),
                'date' => filemtime($filePath),
                'path' => $filePath,
                'is_db_backup' => isDatabaseBackup($file)
            ];
            $backupFiles[] = $fileInfo;
        }
    }
}

/**
 * Check if file is a database backup
 */
function isDatabaseBackup($filename) {
    return strpos($filename, 'db_backup_') === 0 && pathinfo($filename, PATHINFO_EXTENSION) === 'sql';
}

// Format bytes to human readable format
function formatSize($bytes, $precision = 2) {
    $units = ['بایت', 'کیلوبایت', 'مگابایت', 'گیگابایت', 'ترابایت'];
    $bytes = max($bytes, 0);
    $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
    $pow = min($pow, count($units) - 1);
    $bytes /= pow(1024, $pow);
    return number_format($bytes, $precision, '.', ',') . ' ' . $units[$pow];
}

// Start HTML output
?>
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>مدیریت پشتیبان‌گیری</title>
    <link href="../assets/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="../assets/css/font-awesome.min.css" rel="stylesheet" />
    <link href="../assets/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
</head>
<body>
    <?php include __DIR__ . '/header.php'; ?>
    
    <div class="container" style="margin-top: 100px; margin-bottom: 40px;">
        <?php if ($success): ?>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <?php echo $success; ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>
        
        <?php if ($error): ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <?php echo $error; ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php endif; ?>

        <div class="card mb-4">
            <div class="card-header bg-primary text-white d-flex justify-content-between align-items-center">
                <h5 class="card-title mb-0">
                    <i class="bi bi-database-fill-gear me-2"></i>عملیات پشتیبان‌گیری
                </h5>
                <div>
                    <a href="?action=backup_db" class="btn btn-success" onclick="return confirm('آیا از ایجاد پشتیبان از دیتابیس اطمینان دارید؟')">
                        <i class="bi bi-database-check"></i> پشتیبان از دیتابیس
                    </a>
                    <a href="?action=create_backup" class="btn btn-warning text-white" onclick="return confirm('آیا از ایجاد پشتیبان کامل اطمینان دارید؟')">
                        <i class="bi bi-file-earmark-zip"></i> پشتیبان کامل سیستم
                    </a>
                </div>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data" class="row g-3">
                    <div class="col-md-8">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="backup_file" name="backup_file" accept=".zip" required>
                            <label class="custom-file-label" for="backup_file">فایلی انتخاب نشده است</label>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <button type="submit" name="action" value="restore" class="btn btn-primary w-100">
                            <i class="bi bi-upload"></i> بازیابی از پشتیبان
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="card">
            <div class="card-header bg-light">
                <h5 class="card-title mb-0">
                    <i class="bi bi-archive me-2"></i>لیست پشتیبان‌های موجود
                </h5>
            </div>
            <div class="card-body">
                <?php if (empty($backupFiles)): ?>
                    <div class="alert alert-info">هیچ فایل پشتیبانی یافت نشد.</div>
                <?php else: ?>
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>نام فایل</th>
                                    <th>تاریخ ایجاد</th>
                                    <th>نوع</th>
                                    <th>حجم</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($backupFiles as $index => $backup): 
                                    $filePath = $backupDir . $backup['name'];
                                    $isDbBackup = strpos($backup['name'], 'db_backup_') === 0 && pathinfo($backup['name'], PATHINFO_EXTENSION) === 'sql';
                                ?>
                                    <tr>
                                        <td><?php echo $index + 1; ?></td>
                                        <td>
                                            <i class="bi <?php echo $isDbBackup ? 'bi-database' : 'bi-file-earmark-zip'; ?> text-primary me-2"></i>
                                            <?php echo htmlspecialchars($backup['name']); ?>
                                        </td>
                                        <td><?php echo jdate('Y/m/d H:i:s', filemtime($filePath)); ?></td>
                                        <td>
                                            <?php if ($isDbBackup): ?>
                                                <span class="badge bg-info">پایگاه داده</span>
                                            <?php else: ?>
                                                <span class="badge bg-secondary">کامل</span>
                                            <?php endif; ?>
                                        </td>
                                        <td><?php echo formatSize(filesize($filePath)); ?></td>
                                        <td class="text-center">
                                            <a href="../backups/<?php echo urlencode($backup['name']); ?>" 
                                               class="btn btn-sm btn-success" 
                                               download
                                               title="دانلود">
                                                <i class="bi bi-download"></i>
                                            </a>
                                            <a href="?delete=<?php echo urlencode($backup['name']); ?>" 
                                               class="btn btn-sm btn-danger" 
                                               onclick="return confirm('آیا از حذف این فایل پشتیبان اطمینان دارید؟')"
                                               title="حذف">
                                                <i class="bi bi-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <?php include __DIR__ . '/footer.php'; ?>
    
    <script src="../assets/js/bootstrap.bundle.min.js"></script>
    <script>
    // Auto-hide alerts after 5 seconds
    setTimeout(function() {
        var alerts = document.querySelectorAll('.alert');
        alerts.forEach(function(alert) {
            var bsAlert = new bootstrap.Alert(alert);
            bsAlert.close();
        });
    }, 5000);

    // Show selected file name in file input
    document.getElementById('backup_file')?.addEventListener('change', function(e) {
        var fileName = e.target.files[0]?.name || 'فایلی انتخاب نشده است';
        var nextSibling = e.target.nextElementSibling;
        if (nextSibling && nextSibling.classList.contains('custom-file-label')) {
            nextSibling.innerText = fileName;
        }
    });
    </script>
</body>
});
</script>
</body>
</html>